name: release

# Overview ref: https://github.com/googleapis/release-please
# Configuration ref: https://github.com/google-github-actions/release-please-action

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  release:
    name: 🙏 release-please
    # For public repos use runs-on: ubuntu-latest
    # For private repos use runs-on: self-hosted
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: release-please
        uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: simple
          # These bumps are honoured only if there is an
          # initial tag of v0.1.0 . Create it manually if needed.
          #
          # BREAKING CHANGE only bumps semver minor if version < 1.0.0
          bump-minor-pre-major: true
          # feat commits bump semver patch instead of minor if version < 1.0.0
          bump-patch-for-minor-pre-major: true
